general:
  system: 0
  pseudo: 0
  log_data: 1
  print_path: 0
  max_iter: 1000000
  max_time: 0.10000000000000001
  time_limit: 0.10000000000000001
rrt_params:
  goal_bias: 1.0
  random_seed: 0
destinations:
  source_id: 808
  objective_ids: [56, 1053, 10, 20, 30, 40, 50, 60, 90, 100, 200, 300, 400, 600]
  target_id: 560
map:
  type: 1
  path: /home/zephyr/Programming/ROS2-SP-APPs/SP_Metric_Opt/applications/tsp_solver_osm/osm_data/
  name: sanf.osm
rtsp_settings:
  shortcut: 1
  swapping: 1
  genetic: 1
  ga:
    random_seed: 0
    mutation_iter: 10000
    population: 1000
    generation: 5