tasks:
  - id: 0
    name: TSP
    processorId: 0
    scheduling_policy: SCHED_FIFO
    priority: 5
  - id: 1
    name: MPC
    processorId: 1
    scheduling_policy: SCHED_FIFO
    priority: 4
  - id: 2
    name: RRT
    processorId: 1
    scheduling_policy: SCHED_FIFO
    priority: 3
  - id: 3
    name: SLAM
    processorId: 0
    scheduling_policy: SCHED_FIFO
    priority: 2