tasks:
  - id: 0
    name: TSP
    processorId: 0
    scheduling_policy: SCHED_OTHER
    priority: 0
  - id: 1
    name: MPC
    processorId: 1
    scheduling_policy: SCHED_OTHER
    priority: 0
  - id: 2
    name: RRT
    processorId: 1
    scheduling_policy: SCHED_OTHER
    priority: 0
  - id: 3
    name: SLAM
    processorId: 0
    scheduling_policy: SCHED_OTHER
    priority: 0